services:
    knp_rad_prototype.prototype.method.touter.generate_url:
        class: Knp\Rad\Prototype\Prototype\Method
        public: false
        arguments:
            - @router
            - generate
        tags:
            - { name: knp_rad_prototype.prototype_method, alias: generateUrl, domain: router }
